export const CommonType = {
  SHOW_ERROR: 'COMMON_SHOW_ERROR',
  HIDE_ERROR: 'COMMON_HIDE_ERROR',

  REQUEST_START: 'COMMON_REQUEST_START',
  REQUEST_END: 'COMMON_REQUEST_END',
  MOCK_REQUEST: 'MOCK_REQUEST', // Only for mock UI

  SHOW_MESSAGE: 'COMMON_SHOW_MESSAGE',
  HIDE_MESSAGE: 'COMMON_HIDE_MESSAGE',

  SHOW_CONFIRM: 'COMMON_SHOW_CONFIRM',
  HIDE_CONFIRM: 'COMMON_HIDE_CONFIRM',
};

export const AccountType = {
  SET_ACCOUNT_STATE: 'SET_ACCOUNT_STATE',
  LOGIN: 'LOGIN',
};

export const HomeType = {
  SET_HOME_STATE: 'SET_HOME_STATE',
  MOVIE_LIST: 'MOVIE_LIST',
};

export const PersistType = {
  SET_PERSIST_STATE: 'SET_PERSIST_STATE',
};
